pipeline {
    agent any
    //options {
     //   skipStagesAfterUnstable()
    //}
    environment {
        SONARQUBE_ENV = 'SonarQube'
    }
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "Jenkins-maven"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    sh 'mvn sonar:sonar'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
